### ISSUE TITLE
Unexpected library names from Muse.

### ISSUE THREAD

**Issue by kutschke** [Mu2e/Muse#73]
When I moved Sandbox into it's own repo, the libraries built by Muse have an unexpected name.   The new repo is Sandbox; to avoid Sandbox/Sandbox and make room for future expansion I renamed the directory to FromOffline.  The libraries as built by Muse are named
```
libsandboxFromOffline_*
```
Note the missing underscore between the repo name and the directory name.

To reproduce
```
setup mu2e
git clone https://github.com/kutschke/Offline
cd Offline
git checkout removeSandbox
cd ..
git clone https://github.com/Mu2e/Sandbox
muse setup
muse build -j 24
ls build/sl7-prof-e20-p033/Sandbox/lib/
```

**Comment by rlcee** [comment]
fixed in #74, deployed 10/26/22 10:26 as v3_05_03 and current
